apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  template: 
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: karima/repository1:nginx-1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
 name: helloworld
spec:
 type: LoadBalancer
 selector:
   app: helloworld
 ports:
   - name: client
     protocol: TCP
     port: 80
 selector:
   app: helloworld
